tasks:
  - before: nvm install 18
    init: |
      cd examples/magento-graphcms
      yarn
      yarn codegen
    command: cd /workspace/graphcommerce/examples/magento-graphcms && npm run dev
vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - esbenp.prettier-vscode
    - GraphQL.vscode-graphql
    - mikestead.DotENV
    - mrorz.language-gettext
    - redhat.vscode-yaml
